{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.vault.secretName }}
  labels:
    {{- include "painel.labels" . | nindent 4 }}
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: {{ .Values.vault.secretStoreRef }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.vault.secretName }}
    creationPolicy: Owner
  dataFrom:
    {{- range .Values.vault.vaultpaths }}
    - extract:
        key: {{ . }}
    {{- end }}
{{- end }}
