# Generated by Django 5.2.10 on 2026-01-18 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=2560, unique=True, verbose_name='nome do arquivo')),
                ('curso_nome', models.CharField(max_length=2560, verbose_name='nome do curso')),
                ('curso_codigo', models.CharField(blank=True, max_length=2560, null=True, verbose_name='código do curso')),
                ('disciplina_codigo', models.CharField(blank=True, max_length=2560, null=True, verbose_name='código da disciplina')),
                ('disciplina_nome', models.CharField(blank=True, max_length=2560, null=True, verbose_name='nome da disciplina')),
                ('disciplina_tipo', models.CharField(blank=True, max_length=2560, null=True, verbose_name='tipo da disciplina')),
                ('turma_codigo', models.CharField(blank=True, max_length=2560, null=True, verbose_name='código da turma')),
                ('ano_periodo', models.CharField(blank=True, max_length=2560, null=True, verbose_name='ano/periodo')),
                ('campus_sigla', models.CharField(blank=True, max_length=2560, null=True, verbose_name='sigla do campus')),
                ('diario_id', models.CharField(blank=True, max_length=2560, null=True, verbose_name='id do diário')),
                ('diario_tipo', models.CharField(blank=True, max_length=2560, null=True, verbose_name='tipo de diário')),
                ('diario_codigo', models.CharField(blank=True, max_length=2560, null=True, verbose_name='código do diário')),
                ('eh_sala_coordenacao', models.BooleanField(default=False, verbose_name='é sala de coordenação')),
                ('tem_certificado', models.BooleanField(default=False, verbose_name='tem certificado')),
                ('carga_horaria', models.CharField(blank=True, max_length=2560, null=True, verbose_name='carga horária')),
                ('url_com_dados', models.URLField(max_length=2560, unique=True, verbose_name='URL com dados')),
                ('url_sem_dados', models.URLField(max_length=2560, unique=True, verbose_name='URL sem dados')),
            ],
            options={
                'verbose_name': 'backup',
                'verbose_name_plural': 'backups',
            },
        ),
        migrations.CreateModel(
            name='DonoBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, unique=True, verbose_name='usuário')),
                ('nome', models.CharField(max_length=2560, verbose_name='nome do dono do backup')),
                ('email', models.EmailField(blank=True, max_length=2560, null=True, verbose_name='e-mail')),
            ],
            options={
                'verbose_name': 'dono',
                'verbose_name_plural': 'donos',
            },
        ),
        migrations.CreateModel(
            name='DonoArquivoBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(blank=True, max_length=2560, null=True, verbose_name='papel original no curso')),
                ('arquivo_backup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backup.arquivobackup')),
                ('dono_backup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backup.donobackup')),
            ],
            options={
                'verbose_name': 'dono de backup',
                'verbose_name_plural': 'donos de backups',
            },
        ),
    ]
