# Generated by Django 6.0.8 on 2026-08-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backup", "0002_alter_arquivobackup_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arquivobackup",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="donoarquivobackup",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="donobackup",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
