# Generated by Django 5.0.2 on 2024-04-05 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4", "0007_alter_usuario_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalusuario",
            name="campus",
        ),
        migrations.RemoveField(
            model_name="historicalusuario",
            name="curso",
        ),
        migrations.RemoveField(
            model_name="historicalusuario",
            name="polo",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="campus",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="curso",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="polo",
        ),
    ]
