# Generated by Django 5.0.3 on 2024-05-06 18:08

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4", "0008_remove_historicalusuario_campus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalusuario",
            name="email",
            field=models.EmailField(
                max_length=2560, null=True, verbose_name="e-Mail preferêncial"
            ),
        ),
        migrations.AlterField(
            model_name="historicalusuario",
            name="email_academico",
            field=models.EmailField(
                blank=True, max_length=2560, null=True, verbose_name="e-Mail academico"
            ),
        ),
        migrations.AlterField(
            model_name="historicalusuario",
            name="email_corporativo",
            field=models.EmailField(
                blank=True,
                max_length=2560,
                null=True,
                verbose_name="e-Mail corporativo",
            ),
        ),
        migrations.AlterField(
            model_name="historicalusuario",
            name="email_google_classroom",
            field=models.EmailField(
                blank=True,
                max_length=2560,
                null=True,
                verbose_name="e-Mail Gogole Classroom",
            ),
        ),
        migrations.AlterField(
            model_name="historicalusuario",
            name="email_secundario",
            field=models.EmailField(
                blank=True, max_length=2560, null=True, verbose_name="e-Mail pessoal"
            ),
        ),
        migrations.AlterField(
            model_name="historicalusuario",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=2560, null=True, verbose_name="primeiro nome"
            ),
        ),
        migrations.AlterField(
            model_name="historicalusuario",
            name="foto",
            field=models.CharField(
                blank=True, max_length=2560, null=True, verbose_name="URL da foto"
            ),
        ),
        migrations.AlterField(
            model_name="historicalusuario",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=2560, null=True, verbose_name="último nome"
            ),
        ),
        migrations.AlterField(
            model_name="historicalusuario",
            name="nome",
            field=models.CharField(
                blank=True, max_length=2560, null=True, verbose_name="nome no SUAP"
            ),
        ),
        migrations.AlterField(
            model_name="historicalusuario",
            name="nome_registro",
            field=models.CharField(
                blank=True, max_length=2560, null=True, verbose_name="nome civil"
            ),
        ),
        migrations.AlterField(
            model_name="historicalusuario",
            name="nome_social",
            field=models.CharField(
                blank=True, max_length=2560, null=True, verbose_name="nome social"
            ),
        ),
        migrations.AlterField(
            model_name="historicalusuario",
            name="nome_usual",
            field=models.CharField(
                blank=True,
                max_length=2560,
                null=True,
                verbose_name="nome de apresentação",
            ),
        ),
        migrations.AlterField(
            model_name="historicalusuario",
            name="tipo_usuario",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Servidor (Docente)", "Servidor (Docente)"),
                    (
                        "Servidor (Técnico-Administrativo)",
                        "Servidor (Técnico-Administrativo)",
                    ),
                    ("Prestador de Serviço", "Prestador de Serviço"),
                    ("Aluno", "Aluno"),
                    ("desconhecido", "Desconhecido"),
                ],
                max_length=2560,
                null=True,
                verbose_name="tipo",
            ),
        ),
        migrations.AlterField(
            model_name="historicalusuario",
            name="username",
            field=models.CharField(
                db_index=True,
                error_messages={"unique": "A user with that IFRN-id already exists."},
                max_length=2560,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="IFRN-id",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                max_length=2560, null=True, verbose_name="e-Mail preferêncial"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email_academico",
            field=models.EmailField(
                blank=True, max_length=2560, null=True, verbose_name="e-Mail academico"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email_corporativo",
            field=models.EmailField(
                blank=True,
                max_length=2560,
                null=True,
                verbose_name="e-Mail corporativo",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email_google_classroom",
            field=models.EmailField(
                blank=True,
                max_length=2560,
                null=True,
                verbose_name="e-Mail Gogole Classroom",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email_secundario",
            field=models.EmailField(
                blank=True, max_length=2560, null=True, verbose_name="e-Mail pessoal"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=2560, null=True, verbose_name="primeiro nome"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="foto",
            field=models.CharField(
                blank=True, max_length=2560, null=True, verbose_name="URL da foto"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=2560, null=True, verbose_name="último nome"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nome",
            field=models.CharField(
                blank=True, max_length=2560, null=True, verbose_name="nome no SUAP"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nome_registro",
            field=models.CharField(
                blank=True, max_length=2560, null=True, verbose_name="nome civil"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nome_social",
            field=models.CharField(
                blank=True, max_length=2560, null=True, verbose_name="nome social"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nome_usual",
            field=models.CharField(
                blank=True,
                max_length=2560,
                null=True,
                verbose_name="nome de apresentação",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="tipo_usuario",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Servidor (Docente)", "Servidor (Docente)"),
                    (
                        "Servidor (Técnico-Administrativo)",
                        "Servidor (Técnico-Administrativo)",
                    ),
                    ("Prestador de Serviço", "Prestador de Serviço"),
                    ("Aluno", "Aluno"),
                    ("desconhecido", "Desconhecido"),
                ],
                max_length=2560,
                null=True,
                verbose_name="tipo",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that IFRN-id already exists."},
                max_length=2560,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="IFRN-id",
            ),
        ),
    ]
