# Generated by Django 5.2 on 2025-05-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4', '0009_alter_historicalusuario_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusuario',
            name='settings',
            field=models.JSONField(blank=True, null=True, verbose_name='configurações'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='settings',
            field=models.JSONField(blank=True, null=True, verbose_name='configurações'),
        ),
    ]
