# Generated by Django 6.0.5 on 2026-05-22 17:53

from django.db import migrations, models

import a4.models


class Migration(migrations.Migration):

    dependencies = [
        ("a4", "0011_historicalusuario_observacao_erro_vinculo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalusuario",
            name="tipo_usuario",
            field=models.CharField(
                blank=True,
                choices=a4.models.TipoUsuario.choices,
                max_length=2560,
                null=True,
                verbose_name="tipo",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="tipo_usuario",
            field=models.CharField(
                blank=True,
                choices=a4.models.TipoUsuario.choices,
                max_length=2560,
                null=True,
                verbose_name="tipo",
            ),
        ),
    ]
