# -*- coding: utf-8 -*-
from settings.apps import *  # noqa
from settings.caches import *  # noqa
from settings.databases import *  # noqa
from settings.emails import *  # noqa
from settings.internationalizations import *  # noqa
from settings.loggings import *  # noqa
from settings.middlewares import *  # noqa
from settings.observabilities import *  # noqa
from settings.routings import *  # noqa
from settings.sass import *  # noqa
from settings.sessions import *  # noqa
from settings.securities import *  # noqa
from settings.templates import *  # noqa
from settings.developments import *  # noqa

# Generated by 'django-admin startproject' using Django 5.0.2.
# https://docs.djangoproject.com/en/5.0/fhowto/deployment/checklist/
# https://docs.djangoproject.com/en/5.0/topics/settings/
# https://docs.djangoproject.com/en/5.0/ref/settings/
