# -*- coding: utf-8 -*-
from sc4py.env import env, env_as_bool, env_as_int


SESSION_KEY = env("DJANGO_SESSION_KEY", "painelava")
SESSION_COOKIE_NAME = env("DJANGO_SESSION_COOKIE_NAME", "%s_sessionid" % SESSION_KEY)
SESSION_COOKIE_AGE = env_as_int("DJANGO_SESSION_COOKIE_AGE", 1209600)
SESSION_COOKIE_DOMAIN = env("DJANGO_SESSION_COOKIE_DOMAIN", None)
SESSION_COOKIE_HTTPONLY = env_as_bool("DJANGO_SESSION_COOKIE_HTTPONLY", False)
SESSION_COOKIE_PATH = env("DJANGO_SESSION_COOKIE_PATH", "/")
SESSION_COOKIE_SAMESITE = env("DJANGO_SESSION_COOKIE_SAMESITE", "Lax")
SESSION_COOKIE_SECURE = env_as_bool("DJANGO_SESSION_COOKIE_SECURE", False)
SESSION_EXPIRE_AT_BROWSER_CLOSE = env_as_bool("DJANGO_SESSION_EXPIRE_AT_BROWSER_CLOSE", False)
SESSION_FILE_PATH = env("DJANGO_SESSION_FILE_PATH", None)
SESSION_SAVE_EVERY_REQUEST = env_as_bool("DJANGO_SESSION_SAVE_EVERY_REQUEST", False)
SESSION_SERIALIZER = env("DJANGO_SESSION_SERIALIZER", "django.contrib.sessions.serializers.JSONSerializer")
SESSION_ENGINE = env("DJANGO_SESSION_ENGINE", "django.contrib.sessions.backends.cache")
SESSION_CACHE_ALIAS = "default"
