# Generated by Django 4.2.4 on 2023-08-11 16:14

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import painel.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("painel", "0008_popup_historicalpopup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Papel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "nome",
                    models.CharField(max_length=256, verbose_name="nome do papel"),
                ),
                (
                    "sigla",
                    models.CharField(blank=True, max_length=10, unique=True, verbose_name="sigla"),
                ),
                (
                    "contexto",
                    models.CharField(
                        choices=[("c", "Curso"), ("p", "Pólo")],
                        max_length=1,
                        verbose_name="contexto",
                    ),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
            ],
            options={
                "verbose_name": "papel",
                "verbose_name_plural": "papéis",
                "ordering": ["nome"],
            },
            bases=(painel.models.ActiveMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name="ambiente",
            name="sigla",
        ),
        migrations.RemoveField(
            model_name="historicalambiente",
            name="sigla",
        ),
        migrations.AlterField(
            model_name="ambiente",
            name="cor_degrade",
            field=models.CharField(
                help_text="Escolha uma cor em RGB.\n                Ex.: <span style='background: #53296d; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#53296d</span> <span style='background: #203d60; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#203d60</span> <span style='background: #315810; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#315810</span>\n                <span style='background: #ae8133; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#ae8133</span> <span style='background: #d05623; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#d05623</span> <span style='background: #fd7941; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#fd7941</span> <span style='background: #09afc0; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#09afc0</span>",
                max_length=255,
                verbose_name="cor do degradê",
            ),
        ),
        migrations.AlterField(
            model_name="ambiente",
            name="cor_mestra",
            field=models.CharField(
                help_text="Escolha uma cor em RGB.\n                Ex.: <span style='background: #a04ed0; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#a04ed0</span> <span style='background: #396ba7; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#396ba7</span> <span style='background: #559c1a; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#559c1a</span>\n                <span style='background: #fabd57; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#fabd57</span> <span style='background: #fd7941; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#fd7941</span> <span style='background: #f54f3b; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#f54f3b</span> <span style='background: #2dcfe0; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#2dcfe0</span>",
                max_length=255,
                verbose_name="cor mestra",
            ),
        ),
        migrations.AlterField(
            model_name="ambiente",
            name="cor_progresso",
            field=models.CharField(
                help_text="Escolha uma cor em RGB.\n                Ex.: <span style='background: #ecdafa; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#ecdafa</span> <span style='background: #b4d0f2; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#b4d0f2</span> <span style='background: #d2f4b7; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#d2f4b7</span>\n                <span style='background: #ffebca; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#ffebca</span> <span style='background: #ffd1be; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#ffd1be</span> <span style='background: #ffbab2; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#ffbab2</span> <span style='background: #d2f2f5; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#d2f2f5</span>",
                max_length=255,
                verbose_name="cor do progresso",
            ),
        ),
        migrations.AlterField(
            model_name="historicalambiente",
            name="cor_degrade",
            field=models.CharField(
                help_text="Escolha uma cor em RGB.\n                Ex.: <span style='background: #53296d; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#53296d</span> <span style='background: #203d60; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#203d60</span> <span style='background: #315810; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#315810</span>\n                <span style='background: #ae8133; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#ae8133</span> <span style='background: #d05623; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#d05623</span> <span style='background: #fd7941; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#fd7941</span> <span style='background: #09afc0; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#09afc0</span>",
                max_length=255,
                verbose_name="cor do degradê",
            ),
        ),
        migrations.AlterField(
            model_name="historicalambiente",
            name="cor_mestra",
            field=models.CharField(
                help_text="Escolha uma cor em RGB.\n                Ex.: <span style='background: #a04ed0; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#a04ed0</span> <span style='background: #396ba7; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#396ba7</span> <span style='background: #559c1a; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#559c1a</span>\n                <span style='background: #fabd57; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#fabd57</span> <span style='background: #fd7941; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#fd7941</span> <span style='background: #f54f3b; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#f54f3b</span> <span style='background: #2dcfe0; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#2dcfe0</span>",
                max_length=255,
                verbose_name="cor mestra",
            ),
        ),
        migrations.AlterField(
            model_name="historicalambiente",
            name="cor_progresso",
            field=models.CharField(
                help_text="Escolha uma cor em RGB.\n                Ex.: <span style='background: #ecdafa; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#ecdafa</span> <span style='background: #b4d0f2; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#b4d0f2</span> <span style='background: #d2f4b7; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#d2f4b7</span>\n                <span style='background: #ffebca; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#ffebca</span> <span style='background: #ffd1be; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#ffd1be</span> <span style='background: #ffbab2; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#ffbab2</span> <span style='background: #d2f2f5; color: #fff; padding: 1px 5px;\n                                font-size: 95%; border-radius: 4px;'>#d2f2f5</span>",
                max_length=255,
                verbose_name="cor do progresso",
            ),
        ),
        migrations.CreateModel(
            name="VinculoPolo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                (
                    "colaborador",
                    models.ForeignKey(
                        limit_choices_to={
                            "tipo_usuario__in": [
                                "Servidor (Docente)",
                                "Servidor (Técnico-Administrativo)",
                                "Prestador de Serviço",
                            ]
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vinculos_polos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "papel",
                    models.ForeignKey(
                        limit_choices_to={"contexto": "p"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="painel.papel",
                    ),
                ),
                (
                    "polo",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="painel.polo"),
                ),
            ],
            options={
                "verbose_name": "vínculo no pólo",
                "verbose_name_plural": "vínculos nos pólos",
                "ordering": ["papel", "polo", "colaborador"],
            },
            bases=(painel.models.ActiveMixin, models.Model),
        ),
        migrations.CreateModel(
            name="VinculoCurso",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                (
                    "colaborador",
                    models.ForeignKey(
                        limit_choices_to={
                            "tipo_usuario__in": [
                                "Servidor (Docente)",
                                "Servidor (Técnico-Administrativo)",
                                "Prestador de Serviço",
                            ]
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vinculos_cursos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="painel.curso"),
                ),
                (
                    "papel",
                    models.ForeignKey(
                        limit_choices_to={"contexto": "c"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="painel.papel",
                    ),
                ),
            ],
            options={
                "verbose_name": "vínculo no curso",
                "verbose_name_plural": "vínculos nos cursos",
                "ordering": ["papel", "curso", "colaborador"],
            },
            bases=(painel.models.ActiveMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVinculoPolo",
            fields=[
                (
                    "id",
                    models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={
                            "tipo_usuario__in": [
                                "Servidor (Docente)",
                                "Servidor (Técnico-Administrativo)",
                                "Prestador de Serviço",
                            ]
                        },
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "papel",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"contexto": "p"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="painel.papel",
                    ),
                ),
                (
                    "polo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="painel.polo",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical vínculo no pólo",
                "verbose_name_plural": "historical vínculos nos pólos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVinculoCurso",
            fields=[
                (
                    "id",
                    models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={
                            "tipo_usuario__in": [
                                "Servidor (Docente)",
                                "Servidor (Técnico-Administrativo)",
                                "Prestador de Serviço",
                            ]
                        },
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="painel.curso",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "papel",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"contexto": "c"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="painel.papel",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical vínculo no curso",
                "verbose_name_plural": "historical vínculos nos cursos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPapel",
            fields=[
                (
                    "id",
                    models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "nome",
                    models.CharField(max_length=256, verbose_name="nome do papel"),
                ),
                (
                    "sigla",
                    models.CharField(blank=True, db_index=True, max_length=10, verbose_name="sigla"),
                ),
                (
                    "contexto",
                    models.CharField(
                        choices=[("c", "Curso"), ("p", "Pólo")],
                        max_length=1,
                        verbose_name="contexto",
                    ),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical papel",
                "verbose_name_plural": "historical papéis",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCursoPolo",
            fields=[
                (
                    "id",
                    models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="painel.curso",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "polo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="painel.polo",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pólo do curso",
                "verbose_name_plural": "historical pólos do curso",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="CursoPolo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                (
                    "curso",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="painel.curso"),
                ),
                (
                    "polo",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="painel.polo"),
                ),
            ],
            options={
                "verbose_name": "pólo do curso",
                "verbose_name_plural": "pólos do curso",
                "ordering": ["curso", "polo"],
            },
            bases=(painel.models.ActiveMixin, models.Model),
        ),
    ]
