# Generated by Django 4.2.4 on 2023-08-12 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("painel", "0009_papel_remove_ambiente_sigla_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cursopolo",
            name="campus",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="painel.campus",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcursopolo",
            name="campus",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="painel.campus",
            ),
        ),
        migrations.AddField(
            model_name="historicalvinculocurso",
            name="campus",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="painel.campus",
            ),
        ),
        migrations.AddField(
            model_name="vinculocurso",
            name="campus",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="painel.campus",
            ),
            preserve_default=False,
        ),
    ]
