# Generated by Django 5.1.4 on 2024-12-25 00:51

import django.db.models.deletion
import djrichtextfield.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("painel", "0014_remove_cursopolo_campus_remove_vinculocurso_campus_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contrante",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=256, verbose_name="URL")),
                (
                    "url_logo",
                    models.URLField(max_length=256, verbose_name="URL da logo"),
                ),
                (
                    "titulo",
                    models.CharField(max_length=256, verbose_name="título do painel"),
                ),
                (
                    "nome_contratante",
                    models.CharField(max_length=256, verbose_name="nome do contrante"),
                ),
                (
                    "observacoes",
                    djrichtextfield.models.RichTextField(
                        blank=True, null=True, verbose_name="observações"
                    ),
                ),
                (
                    "rodape",
                    djrichtextfield.models.RichTextField(
                        blank=True, null=True, verbose_name="rodapé"
                    ),
                ),
                (
                    "css_personalizado",
                    models.TextField(
                        blank=True, null=True, verbose_name="CSS personalizado"
                    ),
                ),
                (
                    "menu_personalizado",
                    models.TextField(
                        blank=True, null=True, verbose_name="menu personalizado"
                    ),
                ),
                (
                    "regex_coordenacao",
                    models.TextField(
                        blank=True, null=True, verbose_name="regex coordenação"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="ativo?")),
            ],
            options={
                "verbose_name": "contrante",
                "verbose_name_plural": "contrantes",
                "ordering": ["titulo"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalContrante",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("url", models.URLField(max_length=256, verbose_name="URL")),
                (
                    "url_logo",
                    models.URLField(max_length=256, verbose_name="URL da logo"),
                ),
                (
                    "titulo",
                    models.CharField(max_length=256, verbose_name="título do painel"),
                ),
                (
                    "nome_contratante",
                    models.CharField(max_length=256, verbose_name="nome do contrante"),
                ),
                (
                    "observacoes",
                    djrichtextfield.models.RichTextField(
                        blank=True, null=True, verbose_name="observações"
                    ),
                ),
                (
                    "rodape",
                    djrichtextfield.models.RichTextField(
                        blank=True, null=True, verbose_name="rodapé"
                    ),
                ),
                (
                    "css_personalizado",
                    models.TextField(
                        blank=True, null=True, verbose_name="CSS personalizado"
                    ),
                ),
                (
                    "menu_personalizado",
                    models.TextField(
                        blank=True, null=True, verbose_name="menu personalizado"
                    ),
                ),
                (
                    "regex_coordenacao",
                    models.TextField(
                        blank=True, null=True, verbose_name="regex coordenação"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="ativo?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical contrante",
                "verbose_name_plural": "historical contrantes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
