# Generated by Django 5.1.4 on 2024-12-25 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("painel", "0015_contrante_historicalcontrante"),
    ]

    operations = [
        migrations.AddField(
            model_name="ambiente",
            name="contratante",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="painel.contrante",
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="contratante",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="painel.contrante",
            ),
        ),
        migrations.AddField(
            model_name="historicalambiente",
            name="contratante",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="painel.contrante",
            ),
        ),
        migrations.AddField(
            model_name="historicalcurso",
            name="contratante",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="painel.contrante",
            ),
        ),
        migrations.AddField(
            model_name="historicalpopup",
            name="contratante",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="painel.contrante",
            ),
        ),
        migrations.AddField(
            model_name="popup",
            name="contratante",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="painel.contrante",
            ),
        ),
    ]
