# Generated by Django 5.1.4 on 2024-12-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("painel", "0016_ambiente_contratante_curso_contratante_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curso",
            name="suap_id",
        ),
        migrations.RemoveField(
            model_name="historicalcurso",
            name="suap_id",
        ),
        migrations.AlterField(
            model_name="historicalpopup",
            name="active",
            field=models.BooleanField(default=True, verbose_name="ativo?"),
        ),
        migrations.AlterField(
            model_name="popup",
            name="active",
            field=models.BooleanField(default=True, verbose_name="ativo?"),
        ),
    ]
