# Generated by Django 5.1.4 on 2024-12-25 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("painel", "0017_remove_curso_suap_id_remove_historicalcurso_suap_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curso",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="historicalcurso",
            name="descricao",
        ),
    ]
