# Generated by Django 5.2.1 on 2025-05-15 22:44

import django.db.models.deletion
import painel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("painel", "0018_remove_curso_descricao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="nome do theme"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="ativo?")),
            ],
            options={
                "verbose_name": "tema",
                "verbose_name_plural": "temas",
                "ordering": ["nome"],
            },
            bases=(painel.models.ActiveMixin, models.Model),
        ),
        migrations.AddField(
            model_name="contrante",
            name="useraway_account",
            field=models.TextField(
                blank=True, null=True, verbose_name="código do userway"
            ),
        ),
        migrations.AddField(
            model_name="contrante",
            name="useraway_active",
            field=models.BooleanField(default=False, verbose_name="ativar userway?"),
        ),
        migrations.AddField(
            model_name="contrante",
            name="vlibras_active",
            field=models.TextField(
                blank=True, null=True, verbose_name="ativar vlibras"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontrante",
            name="useraway_account",
            field=models.TextField(
                blank=True, null=True, verbose_name="código do userway"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontrante",
            name="useraway_active",
            field=models.BooleanField(default=False, verbose_name="ativar userway?"),
        ),
        migrations.AddField(
            model_name="historicalcontrante",
            name="vlibras_active",
            field=models.TextField(
                blank=True, null=True, verbose_name="ativar vlibras"
            ),
        ),
        migrations.AddField(
            model_name="contrante",
            name="default_theme",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="painel.theme",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontrante",
            name="default_theme",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="painel.theme",
            ),
        ),
        migrations.CreateModel(
            name="AddedTheme",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="ativo?")),
                (
                    "contratante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="painel.contrante",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="painel.theme"
                    ),
                ),
            ],
            options={
                "verbose_name": "tema autorizado",
                "verbose_name_plural": "temas autorizados",
                "unique_together": {("contratante", "theme")},
            },
            bases=(painel.models.ActiveMixin, models.Model),
        ),
    ]
