# Generated by Django 5.2.6 on 2025-11-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("painel", "0019_theme_contrante_useraway_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="apelido",
            field=models.CharField(
                default="tema", max_length=255, verbose_name="apelido"
            ),
            preserve_default=False,
        ),
    ]
