# Generated by Django 5.2.10 on 2026-01-17 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0021_dev_env'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=2560, verbose_name='nome do curso')),
                ('nome_arquivo', models.CharField(max_length=2560, verbose_name='nome do arquivo')),
                ('url_com_dados', models.URLField(max_length=2560, unique=True, verbose_name='url com dados')),
                ('url_sem_dados', models.URLField(max_length=2560, unique=True, verbose_name='url sem dados')),
            ],
            options={
                'verbose_name': 'arquivo de backup',
                'verbose_name_plural': 'arquivos de backup',
            },
        ),
        migrations.CreateModel(
            name='DonoBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, unique=True, verbose_name='usuário')),
                ('nome', models.CharField(max_length=2560, verbose_name='dono de backup')),
            ],
            options={
                'verbose_name': 'dono de backup',
                'verbose_name_plural': 'donos de backup',
            },
        ),
        migrations.CreateModel(
            name='DonoArquivoBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_backup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='painel.arquivobackup')),
                ('dono_backup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='painel.donobackup')),
            ],
            options={
                'verbose_name': 'dono do arquivo de backup',
                'verbose_name_plural': 'dono dos arquivos de backup',
            },
        ),
    ]
