# Generated by Django 5.2.10 on 2026-01-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0022_arquivobackup_donobackup_donoarquivobackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='donobackup',
            name='email',
            field=models.EmailField(blank=True, max_length=2560, null=True, verbose_name='e-mail'),
        ),
    ]
