# Generated by Django 5.2.10 on 2026-01-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0023_donobackup_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivobackup',
            options={'verbose_name': 'backup', 'verbose_name_plural': 'backups'},
        ),
        migrations.AlterModelOptions(
            name='donoarquivobackup',
            options={'verbose_name': 'dono de backup', 'verbose_name_plural': 'donos de backups'},
        ),
        migrations.AlterModelOptions(
            name='donobackup',
            options={'verbose_name': 'dono', 'verbose_name_plural': 'donos'},
        ),
        migrations.RenameField(
            model_name='arquivobackup',
            old_name='nome_curso',
            new_name='curso_nome',
        ),
        migrations.AddField(
            model_name='arquivobackup',
            name='ano_periodo',
            field=models.CharField(blank=True, max_length=2560, null=True, verbose_name='ano/periodo'),
        ),
        migrations.AddField(
            model_name='arquivobackup',
            name='campus_sigla',
            field=models.CharField(blank=True, max_length=2560, null=True, verbose_name='sigla do campus'),
        ),
        migrations.AddField(
            model_name='arquivobackup',
            name='carga_horaria',
            field=models.CharField(blank=True, max_length=2560, null=True, verbose_name='carga horária'),
        ),
        migrations.AddField(
            model_name='arquivobackup',
            name='curso_codigo',
            field=models.CharField(blank=True, max_length=2560, null=True, verbose_name='código do curso'),
        ),
        migrations.AddField(
            model_name='arquivobackup',
            name='diario_codigo',
            field=models.CharField(blank=True, max_length=2560, null=True, verbose_name='código do diário'),
        ),
        migrations.AddField(
            model_name='arquivobackup',
            name='diario_id',
            field=models.CharField(blank=True, max_length=2560, null=True, verbose_name='id do diário'),
        ),
        migrations.AddField(
            model_name='arquivobackup',
            name='diario_tipo',
            field=models.CharField(blank=True, max_length=2560, null=True, verbose_name='tipo de diário'),
        ),
        migrations.AddField(
            model_name='arquivobackup',
            name='disciplina_codigo',
            field=models.CharField(blank=True, max_length=2560, null=True, verbose_name='código da disciplina'),
        ),
        migrations.AddField(
            model_name='arquivobackup',
            name='disciplina_nome',
            field=models.CharField(blank=True, max_length=2560, null=True, verbose_name='nome da disciplina'),
        ),
        migrations.AddField(
            model_name='arquivobackup',
            name='disciplina_tipo',
            field=models.CharField(blank=True, max_length=2560, null=True, verbose_name='tipo da disciplina'),
        ),
        migrations.AddField(
            model_name='arquivobackup',
            name='eh_sala_coordenacao',
            field=models.BooleanField(default=False, verbose_name='é sala de coordenação'),
        ),
        migrations.AddField(
            model_name='arquivobackup',
            name='tem_certificado',
            field=models.BooleanField(default=False, verbose_name='tem certificado'),
        ),
        migrations.AddField(
            model_name='arquivobackup',
            name='turma_codigo',
            field=models.CharField(blank=True, max_length=2560, null=True, verbose_name='código da turma'),
        ),
        migrations.AddField(
            model_name='donoarquivobackup',
            name='papel',
            field=models.CharField(blank=True, max_length=2560, null=True, verbose_name='dono de backup'),
        ),
        migrations.AlterField(
            model_name='arquivobackup',
            name='nome_arquivo',
            field=models.CharField(max_length=2560, unique=True, verbose_name='nome do arquivo'),
        ),
        migrations.AlterField(
            model_name='arquivobackup',
            name='url_com_dados',
            field=models.URLField(max_length=2560, unique=True, verbose_name='URL com dados'),
        ),
        migrations.AlterField(
            model_name='arquivobackup',
            name='url_sem_dados',
            field=models.URLField(max_length=2560, unique=True, verbose_name='URL sem dados'),
        ),
    ]
