# Generated by Django 5.2.10 on 2026-01-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0024_alter_arquivobackup_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrante',
            name='default_theme',
        ),
        migrations.RemoveField(
            model_name='historicalcurso',
            name='contratante',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='contratante',
        ),
        migrations.RemoveField(
            model_name='historicalpopup',
            name='contratante',
        ),
        migrations.RemoveField(
            model_name='historicalambiente',
            name='contratante',
        ),
        migrations.RemoveField(
            model_name='popup',
            name='contratante',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='contratante',
        ),
        migrations.RemoveField(
            model_name='historicalcontrante',
            name='default_theme',
        ),
        migrations.RemoveField(
            model_name='historicalcontrante',
            name='history_user',
        ),
        migrations.AlterField(
            model_name='donoarquivobackup',
            name='papel',
            field=models.CharField(blank=True, max_length=2560, null=True, verbose_name='papel original no curso'),
        ),
        migrations.AlterField(
            model_name='donobackup',
            name='nome',
            field=models.CharField(max_length=2560, verbose_name='nome do dono do backup'),
        ),
        migrations.DeleteModel(
            name='AddedTheme',
        ),
        migrations.DeleteModel(
            name='Contrante',
        ),
        migrations.DeleteModel(
            name='HistoricalContrante',
        ),
    ]
