# Generated by Django 5.2.10 on 2026-01-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0025_remove_contrante_default_theme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donoarquivobackup',
            name='arquivo_backup',
        ),
        migrations.RemoveField(
            model_name='donoarquivobackup',
            name='dono_backup',
        ),
        migrations.DeleteModel(
            name='ArquivoBackup',
        ),
        migrations.DeleteModel(
            name='DonoArquivoBackup',
        ),
        migrations.DeleteModel(
            name='DonoBackup',
        ),
    ]
