# Generated by Django 6.0.5 on 2026-06-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0027_configuracaoaba_historicalconfiguracaoaba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='cor_mestra',
            field=models.CharField(help_text='Escolha uma cor em RGB. Ex.: #a04ed0 #396ba7 #559c1a #fabd57 #fd7941 #f54f3b #2dcfe0', max_length=255, verbose_name='cor mestra'),
        ),
        migrations.AlterField(
            model_name='historicalambiente',
            name='cor_mestra',
            field=models.CharField(help_text='Escolha uma cor em RGB. Ex.: #a04ed0 #396ba7 #559c1a #fabd57 #fd7941 #f54f3b #2dcfe0', max_length=255, verbose_name='cor mestra'),
        ),
    ]
