name: Pipeline - Painel AVA

on:
  release:
    types: [published]
  workflow_dispatch: # Mantido aqui apenas caso precise rodar manualmente pelo painel do GitHub

env:
  MAIN_IMAGE: ctezlifrn/avapainel

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.release.tag_name || github.ref_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.MAIN_IMAGE }}:${{ github.event.release.tag_name || github.ref_name }}

  deploy:
    needs: publish-docker
    permissions:
      contents: read
    runs-on: [self-hosted, runner-dead]
    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.K8S_HOST }} >> ~/.ssh/known_hosts

      - name: Enviar Chart do Helm
        run: |
          ssh root@${{ secrets.K8S_HOST }} "rm -rf /tmp/painel-chart"
          scp -r ./helm root@${{ secrets.K8S_HOST }}:/tmp/painel-chart

      - name: Executar Upgrade no Helm
        run: |
          # Captura a tag da release atual ou o nome da branch/tag se rodado manualmente
          TARGET_TAG="${{ github.event.release.tag_name || github.ref_name }}"
          
          ssh root@${{ secrets.K8S_HOST }} "
            helm upgrade --install painel /tmp/painel-chart \
              --namespace ava \
              --set image.repository=${{ vars.DOCKERHUB_HOST }}/${{ env.MAIN_IMAGE }} \
              --set image.tag=${TARGET_TAG}
          "