name: Build and Deploy Painel

env:
  MAIN_IMAGE: ctezlifrn/avapainel

on:
  release:
    types: [published]
  workflow_run:
    workflows: ["Publish"]
    types: [completed]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Dockerfiles
        run: |
          for dockerfile in $(find . -iname "*Dockerfile*" -o -iwholename "./Dockerfile"); do
            echo "Starting build for the Dockerfile $dockerfile"
            docker build . --file $dockerfile
          done
        shell: bash

  deploy:
    needs: build
    runs-on: [self-hosted, runner-dead]
    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.K8S_HOST }} >> ~/.ssh/known_hosts

      - name: Enviar Chart do Helm
        run: |
          ssh root@${{ secrets.K8S_HOST }} "rm -rf /tmp/painel-chart"
          scp -r ./helm root@${{ secrets.K8S_HOST }}:/tmp/painel-chart

      - name: Executar Upgrade no Helm
        run: |
          ssh root@${{ secrets.K8S_HOST }} "
            helm upgrade --install painel /tmp/painel-chart \
              --namespace ava \
              --set image.repository=${{ vars.DOCKERHUB_HOST }}/${{ env.MAIN_IMAGE }}
          "
