name: Build and Deploy Painel

env:
  MAIN_IMAGE: ctezlifrn/avapainel

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKERHUB_HOST }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKERHUB_HOST }}/${{ env.MAIN_IMAGE }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: [self-hosted, runner-dead]
    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.K8S_HOST }} >> ~/.ssh/known_hosts

      - name: Enviar Chart do Helm
        run: |
          ssh root@${{ secrets.K8S_HOST }} "rm -rf /tmp/painel-chart"
          scp -r ./helm root@${{ secrets.K8S_HOST }}:/tmp/painel-chart

      - name: Executar Upgrade no Helm
        run: |
          DEPLOY_TAG="${{ github.ref_type == 'tag' && github.ref_name || github.sha }}"

          ssh root@${{ secrets.K8S_HOST }} "
            helm upgrade --install painel /tmp/painel-chart \
              --namespace ava \
              --set image.tag=$DEPLOY_TAG \
              --set image.repository=${{ vars.DOCKERHUB_HOST }}/${{ env.MAIN_IMAGE }}
          "